### ISSUE TITLE
People are Considering Implementing this Library

### ISSUE THREAD

**Issue by paragonie-scott** [Dirktheman/rsa-codeigniter-library#1]
Hi @Dirktheman 

It looks like you wrote this years ago and probably forgot about it by now, but [people are seriously considering implementing it](http://stackoverflow.com/questions/33593140/how-to-generate-signature-and-keys-in-codeigniter-rsa-library) in their projects.

This is concerning, because (as you may know after years of accumulated knowledge since you first wrote it) this library isn't cryptographically secure.

**Comment by IDisposable** [comment]
or even randomly, accidentally sorta-secure

**Comment by alex-hunsley-zonal** [comment]
In the very least the README needs a huge disclaimer saying "Don't use this. It's very insecure."

**Comment by doertedev** [comment]
This disclaimer would have the same effect as the "visitors must be 18 and older+" message on porn sites. This is an excellent example for trainings, but as soon as you publish this it will be copied along until eternity :(

**Comment by Dirktheman** [comment]
Whoa! I completely forgot I had this "gem" still hanging around. You're right, it's not secure at all. I answered the SO question and pull this one down immediately.
